FROM: RHEL7
MAINTAINER: Arul
RUN: yum install -y httpd php php-mysql php-gd php-xml mariadb-server mariadb php-mbstringl \ 
                               systemctl start mariadb ; \
                               mysql_secure_installation ;\
			       mysql -u root -p; \                           
                               CREATE USER 'wiki'@'localhost' IDENTIFIED BY 'THISpasswordSHOULDbeCHANGED ; \
                               CREATE DATABASE wikidatabase ; \
                               GRANT ALL PRIVILEGES ON wikidatabase.* TO 'wiki'@'localhost'; FLUSH PRIVILEGES
CMD: systemctl enable mariadb; systemctl enable httpd
WORKDIR: /home/username
ADD: wget https://releases.wikimedia.org/mediawiki/1.34/mediawiki-1.34.0.tar.gz
RUN: gpg --verify mediawiki-1.34.0.tar.gz.sig mediawiki-1.34.0.tar.gz
WORKDIR: /var/www
ADD: tar -zxf /home/username/mediawiki-1.34.0.tar.gz
RUN: chown -R apache:apache /var/www/mediawiki; \           
               service httpd restart
ENTRYPOINT: ln -s mediawiki-1.34.0/ mediawiki